-- Salwa Musik: sistem pendapatan dan piutang (PostgreSQL / Supabase)
-- Entitas inti: siswa, program_kursus, tagihan, pembayaran.
-- siswa (1) -------- (N) tagihan (N) -------- (1) program_kursus
--                         |
--                        (1)
--                         |
--                        (N) pembayaran
-- Piutang dihitung sebagai jumlah_tagihan dikurangi SUM(pembayaran.jumlah_bayar).
-- Jalankan di SQL Editor Supabase. Data pada empat tabel inti tetap dipertahankan.

-- Hapus objek legacy agar schema berisi tepat empat entitas inti.
DROP TABLE IF EXISTS public.pengeluaran;

CREATE TABLE IF NOT EXISTS public.siswa (
    id_siswa BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_siswa VARCHAR(120) NOT NULL,
    no_telepon VARCHAR(30),
    email VARCHAR(160),
    tanggal_daftar DATE NOT NULL DEFAULT CURRENT_DATE,
    aktif BOOLEAN NOT NULL DEFAULT TRUE,
    dibuat_pada TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.program_kursus (
    id_program BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_program VARCHAR(100) NOT NULL,
    instrumen VARCHAR(80) NOT NULL,
    durasi_menit SMALLINT NOT NULL DEFAULT 45 CHECK (durasi_menit > 0),
    biaya_bulanan NUMERIC(14,2) NOT NULL CHECK (biaya_bulanan > 0),
    aktif BOOLEAN NOT NULL DEFAULT TRUE,
    dibuat_pada TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.program_kursus
    DROP COLUMN IF EXISTS nama_pengajar;

CREATE TABLE IF NOT EXISTS public.tagihan (
    id_tagihan BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_siswa BIGINT NOT NULL REFERENCES public.siswa(id_siswa) ON UPDATE CASCADE ON DELETE RESTRICT,
    id_program BIGINT NOT NULL REFERENCES public.program_kursus(id_program) ON UPDATE CASCADE ON DELETE RESTRICT,
    periode VARCHAR(60) NOT NULL,
    tanggal_terbit DATE NOT NULL DEFAULT CURRENT_DATE,
    tanggal_jatuh_tempo DATE NOT NULL,
    jumlah_tagihan NUMERIC(14,2) NOT NULL CHECK (jumlah_tagihan > 0),
    keterangan TEXT,
    dibuat_pada TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (tanggal_jatuh_tempo >= tanggal_terbit)
);

CREATE TABLE IF NOT EXISTS public.pembayaran (
    id_pembayaran BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tagihan BIGINT NOT NULL REFERENCES public.tagihan(id_tagihan) ON UPDATE CASCADE ON DELETE RESTRICT,
    tanggal_bayar DATE NOT NULL DEFAULT CURRENT_DATE,
    jumlah_bayar NUMERIC(14,2) NOT NULL CHECK (jumlah_bayar > 0),
    metode VARCHAR(30) NOT NULL CHECK (metode IN ('Tunai', 'Transfer bank', 'QRIS', 'Lainnya')),
    referensi VARCHAR(100),
    dibuat_pada TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tagihan_siswa ON public.tagihan(id_siswa);
CREATE INDEX IF NOT EXISTS idx_tagihan_jatuh_tempo ON public.tagihan(tanggal_jatuh_tempo);
CREATE INDEX IF NOT EXISTS idx_pembayaran_tagihan ON public.pembayaran(id_tagihan);
CREATE INDEX IF NOT EXISTS idx_pembayaran_tanggal ON public.pembayaran(tanggal_bayar);

-- Kunci baris tagihan saat pembayaran ditambahkan agar dua pembayaran bersamaan
-- tidak dapat membuat total pembayaran melebihi nilai tagihan.
CREATE OR REPLACE FUNCTION public.validasi_total_pembayaran()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    nilai_tagihan NUMERIC(14,2);
    total_pembayaran NUMERIC(14,2);
BEGIN
    IF TG_OP = 'UPDATE' THEN
        IF NEW.id_tagihan <> OLD.id_tagihan THEN
            RAISE EXCEPTION 'Pembayaran tidak dapat dipindahkan ke tagihan lain.';
        END IF;
    END IF;

    SELECT jumlah_tagihan INTO nilai_tagihan
    FROM public.tagihan
    WHERE id_tagihan = NEW.id_tagihan
    FOR UPDATE;

    IF TG_OP = 'INSERT' THEN
        SELECT COALESCE(SUM(jumlah_bayar), 0) INTO total_pembayaran
        FROM public.pembayaran
        WHERE id_tagihan = NEW.id_tagihan;
    ELSE
        SELECT COALESCE(SUM(jumlah_bayar), 0) INTO total_pembayaran
        FROM public.pembayaran
        WHERE id_tagihan = NEW.id_tagihan
            AND id_pembayaran <> OLD.id_pembayaran;
    END IF;

    IF total_pembayaran + NEW.jumlah_bayar > nilai_tagihan THEN
        RAISE EXCEPTION 'Total pembayaran melebihi nilai tagihan (%).', nilai_tagihan;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS pembayaran_batasi_total ON public.pembayaran;
CREATE TRIGGER pembayaran_batasi_total
BEFORE INSERT OR UPDATE OF id_tagihan, jumlah_bayar ON public.pembayaran
FOR EACH ROW EXECUTE FUNCTION public.validasi_total_pembayaran();

-- Nilai tagihan tidak boleh diturunkan di bawah jumlah yang sudah dibayar.
CREATE OR REPLACE FUNCTION public.validasi_nilai_tagihan()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    total_pembayaran NUMERIC(14,2);
BEGIN
    IF NEW.jumlah_tagihan < OLD.jumlah_tagihan THEN
        SELECT COALESCE(SUM(jumlah_bayar), 0) INTO total_pembayaran
        FROM public.pembayaran
        WHERE id_tagihan = OLD.id_tagihan;

        IF NEW.jumlah_tagihan < total_pembayaran THEN
            RAISE EXCEPTION 'Nilai tagihan tidak boleh lebih kecil dari total pembayaran (%).', total_pembayaran;
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tagihan_batasi_nilai ON public.tagihan;
CREATE TRIGGER tagihan_batasi_nilai
BEFORE UPDATE OF jumlah_tagihan ON public.tagihan
FOR EACH ROW EXECUTE FUNCTION public.validasi_nilai_tagihan();

-- Kebijakan terbuka ini hanya untuk prototipe/tugas tanpa login.
-- Untuk penggunaan nyata, aktifkan Supabase Auth dan ganti dengan kebijakan
-- berbasis pengguna/organisasi sebelum menyimpan data siswa yang sesungguhnya.
ALTER TABLE public.siswa ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.program_kursus ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tagihan ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pembayaran ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS demo_siswa_all ON public.siswa;
DROP POLICY IF EXISTS demo_program_all ON public.program_kursus;
DROP POLICY IF EXISTS demo_tagihan_all ON public.tagihan;
DROP POLICY IF EXISTS demo_pembayaran_all ON public.pembayaran;

CREATE POLICY demo_siswa_all ON public.siswa FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY demo_program_all ON public.program_kursus FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY demo_tagihan_all ON public.tagihan FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY demo_pembayaran_all ON public.pembayaran FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- DATA DEMO: program, siswa, tagihan, dan pembayaran.
-- Dapat dijalankan ulang tanpa menggandakan data demo.
BEGIN;

INSERT INTO public.program_kursus (nama_program, instrumen, durasi_menit, biaya_bulanan)
SELECT 'Kursus Piano Pemula', 'Piano', 45, 600000
WHERE NOT EXISTS (
    SELECT 1 FROM public.program_kursus WHERE nama_program = 'Kursus Piano Pemula'
);

INSERT INTO public.program_kursus (nama_program, instrumen, durasi_menit, biaya_bulanan)
SELECT 'Kursus Gitar Akustik', 'Gitar', 45, 450000
WHERE NOT EXISTS (
    SELECT 1 FROM public.program_kursus WHERE nama_program = 'Kursus Gitar Akustik'
);

INSERT INTO public.program_kursus (nama_program, instrumen, durasi_menit, biaya_bulanan)
SELECT 'Kursus Vokal Dasar', 'Vokal', 45, 400000
WHERE NOT EXISTS (
    SELECT 1 FROM public.program_kursus WHERE nama_program = 'Kursus Vokal Dasar'
);

INSERT INTO public.program_kursus (nama_program, instrumen, durasi_menit, biaya_bulanan)
SELECT 'Kursus Biola Pemula', 'Biola', 45, 550000
WHERE NOT EXISTS (
    SELECT 1 FROM public.program_kursus WHERE nama_program = 'Kursus Biola Pemula'
);

INSERT INTO public.program_kursus (nama_program, instrumen, durasi_menit, biaya_bulanan)
SELECT 'Kursus Drum Pemula', 'Drum', 45, 500000
WHERE NOT EXISTS (
    SELECT 1 FROM public.program_kursus WHERE nama_program = 'Kursus Drum Pemula'
);

INSERT INTO public.program_kursus (nama_program, instrumen, durasi_menit, biaya_bulanan)
SELECT 'Kursus Keyboard Pemula', 'Keyboard', 45, 550000
WHERE NOT EXISTS (
    SELECT 1 FROM public.program_kursus WHERE nama_program = 'Kursus Keyboard Pemula'
);

INSERT INTO public.siswa (nama_siswa)
SELECT demo.nama_siswa
FROM (VALUES
    ('Ahmad Fauzan'),
    ('Bima Pratama'),
    ('Dimas Saputra'),
    ('Fajar Ramadhan'),
    ('Rizky Maulana')
) AS demo(nama_siswa)
WHERE NOT EXISTS (
    SELECT 1 FROM public.siswa WHERE nama_siswa = demo.nama_siswa
);

COMMIT;